### ISSUE TITLE
How to change progress of loading indicator?

### ISSUE THREAD

**Issue by lukeramsden** [NathanWalker/nativescript-loading-indicator#28]
I am showing a loading indicator while I'm uploading a file to Firebase, which also gives me an updating percentage of progress, how would I make the loading indicator represent this?

**Comment by lukeramsden** [comment]
Any chance of a reply to this?

**Comment by sarkar4540** [comment]
I am too having the same problem. Is there any way to do this?

**Comment by LorenDorez** [comment]
i found  this in the demo in relations to iOS
```
 public showLoaderModeCustom() {
    this.indicator.show({ message: 'Completed', ios: { mode: MBProgressHUDMode.CustomView, customView: 'Checkmark.png' } });
    this.demoLoader();
  }
```

**Comment by jujupec** [comment]
for ios.mode, it's not a string but a number. Ex: customview<=>4

**Comment by jujupec** [comment]
in order to change loading progress it's simple : options.progress = a floating number for ios (between 0 and 1 ) and a number for android (between 0 and your options.android.max value). You have to convert your updating percentage.

**Comment by steinerj** [comment]
For me it's seems consistently broken on Android. 

Consider this example:
[https://play.nativescript.org/?template=play-ng&id=u1d37y&v=5](https://play.nativescript.org/?template=play-ng&id=u1d37y&v=5
)

On Android 8.0.0 it always displays an indeterminate spinner, no matter what I specify. It never displays the progress bar.

I'll investigate a bit further...

**Comment by LorenDorez** [comment]
@steinerj Well it might also be due to the fact the this plugin uses the underlying [ProgressDialog ](https://developer.android.com/reference/android/app/ProgressDialog)on android. Which is depreciated as of API 26.

I created a new Loading Screen but havent implemented progress bar yet as i havent had the time yet.

[Loading Screen](https://github.com/LorenDorez/nativescript-loading-screen)

**Comment by steinerj** [comment]
@LorenDorez Fair point! I thought it wasn't removed yet, though. I'm also building against a lower SDK version. So for all intents and purposes it seems broken here and I'm kind of curious to fix it and provide the fix.

I'll give your plugin a spin, since there is a genuine requirement for the indicator to be modal.  Thank you!

**Comment by bradmartin** [comment]
Using the instance of the `LoadingIndicator` class you created. You can call `show` again and pass the `progress` option value. So you'd call it whenever you get your progress event from the events you're monitoring.

```
      this.indicator.show({ progress: 0.35, color });
```

This plugin has now been deprecated and taken over by nStudio, LLC.
https://github.com/nstudio/nativescript-loading-indicator

You can install with `tns plugin add @nstudio/nativescript-loading-indicator`
